version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Cambiar
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: Cambiar
      MARIADB_DATABASE: AcademiaDeIdiomasPEPS
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql

    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
  apache:
    build: ./apache
    container_name: apache
    volumes:
      - ./miweb:/var/www/html
    ports:
      - "9094:80"
    restart: unless-stopped
    depends_on:
      - python
      - mariadb
  python:
    build: .
    container_name: python
    environment:
      DB_USERNAME: root
      DB_PASSWORD: Cambiar
      DB_DATABASE: AcademiaDeIdiomasPEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - 9094:8080
    depends_on:
        - mariadb